# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
services:
  openvpn-client:
    build:
      context: ./docker-openvpn
      dockerfile: Dockerfile.arm
    image: openvpn-aarch64:latest
    container_name: openvpn-client
    environment:
      - DEBUG=1
    cap_add:
      - NET_ADMIN
    networks:
      - bridge_net
    restart: always
    volumes:
     - ./openvpn-data:/etc/openvpn
    command: ["ovpn_client_run", "server.ovpn"]


networks:
  bridge_net:
    driver: bridge
